### ISSUE TITLE
ER - Issue on exercise 3

### ISSUE THREAD

**Issue by lmunier** [lis-epfl/robogen-app#28]
I just reach the following issue after evolving the example file in exercise 3 from the evolutionary robotic course. Work on my Ubuntu 16.04 personal computer.

![exercise3_example_simulation_issue](https://user-images.githubusercontent.com/30860289/56287304-44a2a880-611c-11e9-9005-1c0c6d5d638b.png)

**Comment by anandbaskaran** [comment]
This should be fixed.

Next time please make sure to add more description to the issue.

**Comment by lmunier** [comment]
Thank you to have fixed it. I will take your remark into account next time and explained more into detail the issue I reached.

Best regards,
Louis


-------- Message d'origine --------
De : Anand <notifications@github.com>
Date : 14.05.19 17:05 (GMT+01:00)
À : lis-epfl/robogen-app <robogen-app@noreply.github.com>
Cc : Munier Louis <louis.munier@epfl.ch>, Author <author@noreply.github.com>
Objet : Re: [lis-epfl/robogen-app] ER - Issue on exercise 3 (#28)


This should be fixed.

Next time please make sure to add more description to the issue.
